
export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE'
}

export const userConstants = {
    SIGNUP_REGISTER_REQUEST:'SIGNUP_REGISTER_REQUEST',
    SIGNUP_REGISTER_SUCCESS:'SIGNUP_REGISTER_SUCCESS',
    SIGNUP_REGISTER_FAILURE:'SIGNUP_REGISTER_FAILURE'
}

export const categoryConstants = {
    GETALLCATEGORY_REQUEST:'GETALLCATEGORY_REQUEST',
    GETALLCATEGORY_SUCCESS:'GETALLCATEGORY_SUCCESS',
    GETALLCATEGORY_FAILURE:'GETALLCATEGORY_FAILURE',
    ADDCATEGORY_REQUEST:'ADDCATEGORY_REQUEST',
    ADDCATEGORY_SUCCESS:'ADDCATEGORY_SUCCESS',
    ADDCATEGORY_FAILURE:'ADDCATEGORY_FAILURE'
}

export const productConstants = {
    ADD_PRODUCT_REQUEST:'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS:'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE:'ADD_PRODUCT_FAILURE'
}